spring:
  application:
    name: crm_gateway
  docker:
    compose:
      file: ./ApiGateway/compose.yaml
  cloud:
    gateway:
      mvc:
        http-client:
          type: autodetect
        routes:
          - id: document-store
            uri: http://localhost:8081
            predicates:
              - Path=/document-store/**
            filters:
              - StripPrefix=1
              - TokenRelay
          - id: crm
            uri: http://localhost:8082
            predicates:
              - Path=/crm/**
            filters:
              - StripPrefix=1
              - TokenRelay
          - id : CommunicationManager
            uri: http://localhost:8083
            predicates:
              - Path=/communication-manager/**
            filters:
              - StripPrefix=1
              - TokenRelay
          - id : ui
            uri : http://localhost:5173
            predicates:
              - Path=/ui/**
          - id: home
            uri: http://localhost:8080
            predicates:
              - Path=/
            filters:
              - RedirectTo=301,http://localhost:8080/ui

          - id: grafana
            uri: http://localhost:8080
            predicates:
             - Path=/grafana/**
            filters:
             - RedirectTo=301,http://localhost:3000/




  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:9090/realms/CRM
        registration:
          crmclient:
            provider: keycloak
            client-id: crmclient
            client-secret: dOQVIYfE26xG2UiGSOYzud5tk3YRyNoA
            scope:
              - openid
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/crmclient

management.endpoints.web.exposure.include: '*'
management.endpoint.health.show.details: always