services:
  prometheus:
    image: 'prom/prometheus'
    ports:
      - '9095:9090'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./config_prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config_prometheus/web.yml:/etc/prometheus/web.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.config.file=/etc/prometheus/web.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "$UID:$GID"
    ports:
      - "3000:3000"
    volumes:
      #provisioning
      - ./config_grafana/datasources.yml:/etc/grafana/provisioning/datasources/prometheus.yml
      - ./config_grafana/custom_dashboard.yml:/etc/grafana/provisioning/dashboards/custom_dashboard.yml
      #grafana config file
      - ./config_grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./config_grafana/grafana/:/var/lib/grafana/:rw


    extra_hosts:
      - "host.docker.internal:host-gateway"