services:
  prometheus:
    image: 'prom/prometheus'
    ports:
      - '9095:9090'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
    - "3000:3000"
    volumes:
    - ./datasources.yml:/etc/grafana/provisioning/datasources/prometheus.yml
    - ./grafana.ini:/etc/grafana/grafana.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"