services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    volumes:
      - databaseVolume:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  databaseVolume: