scrape_configs:
  - job_name: 'spring-boot-application-apigateway'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1s # This can be adjusted based on our needs
    static_configs:
      - targets: ['host.docker.internal:8080']
  - job_name: 'spring-boot-application-crm'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1s # This can be adjusted based on our needs
    static_configs:
      - targets: [ 'host.docker.internal:8082' ]