scrape_configs:
  - job_name: 'spring-boot-application-apigateway'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s # This can be adjusted based on our needs
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'spring-boot-application-document-store'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'host.docker.internal:8081' ]

  - job_name: 'spring-boot-application-crm'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'host.docker.internal:8082' ]

  - job_name: 'spring-boot-application-communication-manager'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'host.docker.internal:8083' ]