auth:
  issuer: http://localhost:9090/realms/CRM
spring:
  application:
    name: CRM
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    defer-datasource-initialization: true
  docker:
    compose:
      file: ./CRM/compose.yaml
  mvc:
    problemdetails:
      enabled: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${auth.issuer}
  kafka:
    consumer:
      bootstrap-servers: 127.0.0.1:9092
      group-id: consumer
      auto-offset-reset: earliest
keycloak:
  server-url: http://localhost:9090
  realm: CRM
  client-id: crmclient
  client-secret: dOQVIYfE26xG2UiGSOYzud5tk3YRyNoA
springdoc:
  swagger-ui:
    tags-sorter: alpha
  default-produces-media-type: application/json
server:
  port: 8082
logging:
  level:
    org:
      springframework:
        web: DEBUG

gmail-account:
  application_name: webapp2-2024

gmail:
  client-id: 314430035121-rn507dgme9vaa9i15hrhdo5u7tsths9g.apps.googleusercontent.com
  client-secret: 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
  refresh-token: 1//049ZcWMZqIOUmCgYIARAAGAQSNwF-L9IrJDAMuRsj5a3wP5sKKcEzVUFURNEyS0wf7s8CuqNuwDTNqmRp_hay1ejuFyjUHm-Svhs
  username: webapp2.2024.g07@gmail.com

camel:
  component:
    google-mail-stream:
      application-name: ${gmail-account.application_name}
      client-id: ${gmail.client-id}
      client-secret: ${gmail.client-secret}
      refresh-token: ${gmail.refresh-token}
    google-mail:
      application-name: ${gmail-account.application_name}
      client-id: ${gmail.client-id}
      client-secret: ${gmail.client-secret}
      refresh-token: ${gmail.refresh-token}

management.endpoints.web.exposure.include: '*'
management.endpoint.health.show.details: always
job-placement.document-store-url: http://localhost:8081